exclude: ^src/frontend/frontend/static/.*$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        files: ^(src/core|src/worker|src/frontend|src/models)
      - id: ruff-format
        files: ^(src/core|src/worker|src/frontend|src/models)

  - repo: local
    hooks:
      - id: eslint
        name: lint
        language: node
        entry: pnpm --prefix src/gui run lint_and_format
        files: ^src/gui
        types_or: [javascript, jsx, ts, tsx, vue]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: djlint-reformat-jinja
        name: djlint
        language: system
        files: ^src/frontend/frontend/templates
        entry: uvx djlint --profile=jinja --check
        # pass_filenames: false
        types_or: [jinja, html]

